### ISSUE TITLE
vim-plug install doesn't work 

### ISSUE THREAD

**Issue by cacrespo** [fabridamicelli/cronex.nvim#5] opened 2024-05-01 19:01 UTC
I tried to install `cronex.nvim` using [vim-plug](https://github.com/junegunn/vim-plug) and encountered no errors logs, but the plugin doesn't seem to be working.
```
call plug#begin()
(...)
Plug 'fabridamicelli/cronex.nvim'
(...)
call plug#end()
```

![image](https://github.com/fabridamicelli/cronex.nvim/assets/10950697/8dfb3f29-b155-47e4-ab00-923131949211)
![image](https://github.com/fabridamicelli/cronex.nvim/assets/10950697/bd3118c8-86f0-4b91-96e7-1ae211495d0a)
:´(

I know this is probably  not a `cronex.nvim` issue, but do you have any idea what could be happening?

(I replaced my `init.vim` with `init.lua` and used `lazy.nvim` and everything worked fine. My suspicion is related to optional configuration arguments, but I don't know much about Vim/Neovim).

Congratulations on the pluging. It Looks great!

**Comment by fabridamicelli** [comment] 2024-05-02 08:40
Hi,
thank you for your feedback:)
A few ideas:
- [ ] is the filename you showed in the example one of  { "*.yaml", "*.yml", "*.tf", "*.cfg", "*.config", "*.conf" }? If not, can you run in neovim the command `:CronExplainedEnable` and see if that works?
- [ ] in the normal terminal (where you open neovim) what's the output of running `cronstrue`? If the command does not exist, you need to install cronstrue first (see docu [here](https://github.com/fabridamicelli/cronex.nvim?tab=readme-ov-file#explainer))

Check those points and let me know how it goes

**Comment by cacrespo** [comment] 2024-05-02 12:00
Sorry for not being clear initially:
- [x] the filename is `test.yaml` (in fact, I tested with the different extensions, always with the same result). If I try to enable the plugin inside nvim, the output is `E492: Not an editor command: CronExplainedEnable`
- [x]  `cronstrue` is installed and everything is OK with that.

I don't want to wasted your time. Thanks in advance.

**Comment by fabridamicelli** [comment] 2024-05-02 14:22
@cacrespo Thanks for the reply.
It looks like the setup is not being called.
Can you please run inside neovim this:
`:lua require("cronex").enable()`

does it work now?

(this is not supposed to be the way to activate it, but I want to see if you can use the plugin at all or there is another problem)

**Comment by fabridamicelli** [comment] 2024-05-02 14:39
@cacrespo 
can you also try this (also inside neovim) 
`:lua require("cronex").setup({})`

After that you should be able to call `:CronExplainedEnable`

does that work?

**Comment by cacrespo** [comment] 2024-05-02 16:15
Happy news! 🎉

> Can you please run inside neovim this:
> :lua require("cronex").enable()

It returned this error:
```
E5108: Error executing lua ...los/.config/nvim/plugged/cronex.nvim/lua/cronex/in
it.lua:37: Required: 'command' or 'callback'                                    
stack traceback:                                                                
        [C]: in function 'nvim_create_autocmd'                                  
        ...los/.config/nvim/plugged/cronex.nvim/lua/cronex/init.lua:37: in funct
ion 'enable'                                                                    
        [string ":lua"]:1: in main chunk  
```

However, this command:

> can you also try this (also inside neovim)
> :lua require("cronex").setup({})

Worked perfectly! I can make it available using `:CronExplainedEnable`.

So, I added `:lua require("cronex").setup({})` to my `init.vim` file, and it works smoothly :+1: (without needing to activate it with `:CronExplainedEnable`).  
![image](https://github.com/fabridamicelli/cronex.nvim/assets/10950697/ed799d4d-9270-4601-86ae-85d5bc1563d2)

If you agree, I can add these specifc steps to the README.md.

Thanks!

**Comment by fabridamicelli** [comment] 2024-05-02 16:32
@cacrespo 
Oh great!

I took a look and it seems to be a vim-plug problem indeed in your config.
Can you please try using this in your config instead of the empy call plug#begin() as you showed in the first comment and also without the explicit call to setup in the init.vim:
```vimscript
call plug#begin('~/.config/nvim/plugged')
Plug 'fabridamicelli/cronex.nvim'
call plug#end()
```
Then close neovim and re-open it.Does that work?
I expect that having that should be enough (so that you can remove the explicit call to :lua require("cronex").setup({})
in your config. See for example [here](https://github.com/fisadev/fisa-vim-config/blob/master/config.vim#L66)

Also here's a short [tutorial on how to use vim-plug for neovim plugins](https://www.youtube.com/watch?v=QB9V__3VO2s)

Let me know how that goes and if that doesn't work we can add a little section in the readme for vim-plug users.

PS: [this example in the vim-plug docu](https://github.com/junegunn/vim-plug?tab=readme-ov-file#example-lua-configuration-for-neovim) is also nice

**Comment by cacrespo** [comment] 2024-05-02 16:56
hahah! I also use the fisavim config.
In fact, I thinking right now of writing to recommend this plugin to him.

My first comment was an attempt to simplify my init.vim (as I mentioned, using the fisavim config). 
Here's my actual file:
```
(...)
if using_neovim
    call plug#begin("~/.config/nvim/plugged")
else
    call plug#begin("~/.vim/plugged")
endif

" Now the actual plugins:

" Human-readable inline cron expression
Plug 'fabridamicelli/cronex.nvim'
(...)
call plug#end()
``` 
:point_up: It didn't work for me.

**Comment by fabridamicelli** [comment] 2024-05-02 20:25
Ok, thank you for your code snippet. I just managed to reproduce you're scenario.
You're right, the readme was missing the information to properly setup the plugin using vim-plug, which needs the explicit call inside the config.
I just [pushed the update](https://github.com/fabridamicelli/cronex.nvim/commit/fbdd21555cf1e7a6c2de26724a12600e13f5a549) so the readme should now be more clear.
So I am closing this issue as resolved, feel free to open a new one if [the documentation](https://github.com/fabridamicelli/cronex.nvim?tab=readme-ov-file#installation)  is not enough.
Thanks again for your feedback!

**Closed as completed by fabridamicelli** 2024-05-02 20:25 UTC
